### ISSUE TITLE
Fix 'Ansible / Docker / systemd' issue

### ISSUE THREAD

**Issue by sebthebert** [sebthebert/ansible-role-octopussy#7]
https://github.com/ansible/ansible/issues/30192

**Comment by sebthebert** [comment]
It's actually not an Octopussy Ansible Role issue...

To run a container with systemd:
```
        privileged: yes
        security_opts:
          - seccomp:unconfined
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

Source:
https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container/
